import { useId, useMemo } from 'react'

/**
 * Stand-in for a plate. Fills whatever box it is dropped into, so it can be
 * swapped one-for-one with an <img> or <video>.
 *
 * Deliberately has no frame marks, no reticle and no caption — it reads as a
 * heavily defocused frame rather than a viewfinder. The composition is derived
 * from `seed`, so a project always looks the same and no two cards match.
 */

// Small deterministic string hash (FNV-1a). Good enough to spread the knobs.
function hash(str) {
  let h = 0x811c9dc5
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i)
    h = Math.imul(h, 0x01000193)
  }
  return h >>> 0
}

// Repeatable stream of 0..1 numbers from that hash.
function rng(seed) {
  let s = hash(seed) || 1
  return () => {
    s ^= s << 13
    s ^= s >>> 17
    s ^= s << 5
    s >>>= 0
    return s / 0xffffffff
  }
}

/**
 * Neutral by design: the interface carries no colour, and these are stand-ins
 * generated by the site rather than real artwork — a tinted placeholder would
 * be the only coloured thing on screen that is not the user's own work.
 *
 * Each entry is a lit key and the shadow it falls into. `spec` is the blown-out
 * highlight the bokeh discs use, which keeps these reading as graded frames
 * rather than wallpaper. Variety comes from exposure and contrast, not hue.
 */
const PALETTES = [
  { key: [118, 118, 118], shadow: [16, 16, 16], spec: [236, 236, 236] }, // bright key
  { key: [82, 82, 82], shadow: [12, 12, 12], spec: [206, 206, 206] }, // low key
  { key: [142, 142, 142], shadow: [22, 22, 22], spec: [246, 246, 246] }, // blown out
  { key: [96, 96, 96], shadow: [10, 10, 10], spec: [188, 188, 188] }, // deep shadow
  { key: [128, 128, 128], shadow: [26, 26, 26], spec: [220, 220, 220] }, // flat, lifted
  { key: [70, 70, 70], shadow: [14, 14, 14], spec: [224, 224, 224] }, // high contrast
]

const rgb = (c) => `rgb(${c[0]} ${c[1]} ${c[2]})`

export default function Placeholder({ seed = 'default', label, motion = false, className = '' }) {
  const uid = useId().replace(/:/g, '')

  const art = useMemo(() => {
    const rand = rng(seed)
    const pal = PALETTES[Math.floor(rand() * PALETTES.length)]

    /**
     * Where the light sits in frame; everything else is placed relative to it.
     *
     * The square viewBox is scaled with `slice`, so on a 16:9 box only y≈22–78
     * survives the crop and on 21:9 only y≈29–71. Composition therefore has to
     * stay inside that band or the light source ends up off-frame.
     */
    const keyX = 24 + rand() * 52
    const keyY = 37 + rand() * 26

    /**
     * Out-of-focus highlights. These are what actually sell the image as a
     * defocused plate — a pure gradient wash just reads as a smudge. They stay
     * only lightly blurred so they keep a disc edge against the soft wash.
     */
    const bokeh = Array.from({ length: 11 }, (_, i) => {
      const spread = 14 + rand() * 30
      const warm = i % 4 === 0 // a few embers among the key-coloured discs
      return {
        cx: keyX + (rand() - 0.5) * spread * 2,
        // Vertical scatter stays tight — see the crop note above.
        cy: keyY + (rand() - 0.5) * spread * 0.62,
        r: 1.6 + rand() * rand() * 5.5, // biased small, occasional big one
        o: 0.14 + rand() * 0.4,
        warm,
      }
    })

    return {
      pal,
      keyX,
      keyY,
      keyR: 38 + rand() * 22,
      fillX: 12 + rand() * 76,
      fillY: 56 + rand() * 20,
      fillR: 36 + rand() * 24,
      bokeh,
      // Anamorphic streak through the highlight, the way a real lens flares.
      streakY: keyY + (rand() - 0.5) * 14,
      streakTilt: -7 + rand() * 14,
      streakOpacity: 0.05 + rand() * 0.05,
      drift: rand() > 0.5 ? 1 : -1,
    }
  }, [seed])

  const { pal } = art

  return (
    <div
      className={`ph ${motion ? 'ph--motion' : ''} ${className}`.trim()}
      role="img"
      aria-label={label ? `${label} — placeholder artwork` : 'Placeholder artwork'}
      style={{ '--ph-drift': art.drift }}
    >
      {/* Uniform scale + crop keeps the bokeh discs round whatever the aspect
          of the box; preserveAspectRatio="none" would stretch them to ovals. */}
      <svg
        className="ph__svg"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid slice"
        aria-hidden="true"
      >
        <defs>
          <radialGradient id={`${uid}-key`}>
            <stop offset="0%" stopColor={rgb(pal.key)} stopOpacity="0.6" />
            <stop offset="100%" stopColor={rgb(pal.key)} stopOpacity="0" />
          </radialGradient>
          <radialGradient id={`${uid}-fill`}>
            <stop offset="0%" stopColor={rgb(pal.shadow)} stopOpacity="0.95" />
            <stop offset="100%" stopColor={rgb(pal.shadow)} stopOpacity="0" />
          </radialGradient>
          {/* An out-of-focus highlight: hot core, soft shoulder, faint rim —
              the same falloff a real lens gives a defocused point of light. */}
          <radialGradient id={`${uid}-disc`}>
            <stop offset="0%" stopColor={rgb(pal.spec)} stopOpacity="0.95" />
            <stop offset="62%" stopColor={rgb(pal.spec)} stopOpacity="0.55" />
            <stop offset="88%" stopColor={rgb(pal.spec)} stopOpacity="0.22" />
            <stop offset="100%" stopColor={rgb(pal.spec)} stopOpacity="0" />
          </radialGradient>
          {/* Was a warm ember disc; now just a hotter neutral one, so a few
              highlights still pop without introducing a hue. */}
          <radialGradient id={`${uid}-disc-warm`}>
            <stop offset="0%" stopColor="rgb(255 255 255)" stopOpacity="0.95" />
            <stop offset="62%" stopColor="rgb(238 238 238)" stopOpacity="0.5" />
            <stop offset="88%" stopColor="rgb(200 200 200)" stopOpacity="0.2" />
            <stop offset="100%" stopColor="rgb(200 200 200)" stopOpacity="0" />
          </radialGradient>
          <linearGradient id={`${uid}-streak`} x1="0" y1="0" x2="1" y2="0">
            <stop offset="0%" stopColor={rgb(pal.spec)} stopOpacity="0" />
            <stop offset="50%" stopColor={rgb(pal.spec)} stopOpacity={art.streakOpacity} />
            <stop offset="100%" stopColor={rgb(pal.spec)} stopOpacity="0" />
          </linearGradient>
          <linearGradient id={`${uid}-base`} x1="0" y1="0" x2="0.25" y2="1">
            <stop offset="0%" stopColor={rgb(pal.shadow.map((v) => Math.round(v * 0.9)))} />
            <stop offset="100%" stopColor="#070707" />
          </linearGradient>
          {/* Two focus depths: the wash is thrown far out, the discs only just
              enough to lose their edge. One blur for both would flatten them. */}
          <filter id={`${uid}-soft`} x="-40%" y="-40%" width="180%" height="180%">
            <feGaussianBlur stdDeviation="8" />
          </filter>
          <filter id={`${uid}-bokeh`} x="-30%" y="-30%" width="160%" height="160%">
            <feGaussianBlur stdDeviation="0.85" />
          </filter>
          {/* Weighted to the bottom so the frame has a foreground to sit on. */}
          <linearGradient id={`${uid}-floor`} x1="0" y1="0" x2="0" y2="1">
            <stop offset="45%" stopColor="#000" stopOpacity="0" />
            <stop offset="100%" stopColor="#000" stopOpacity="0.8" />
          </linearGradient>
          <radialGradient id={`${uid}-vig`}>
            <stop offset="50%" stopColor="#000" stopOpacity="0" />
            <stop offset="100%" stopColor="#000" stopOpacity="0.68" />
          </radialGradient>
        </defs>

        <rect width="100" height="100" fill={`url(#${uid}-base)`} />

        <g filter={`url(#${uid}-soft)`}>
          <ellipse
            cx={art.fillX}
            cy={art.fillY}
            rx={art.fillR}
            ry={art.fillR * 0.72}
            fill={`url(#${uid}-fill)`}
          />
          <ellipse
            cx={art.keyX}
            cy={art.keyY}
            rx={art.keyR}
            ry={art.keyR * 0.66}
            fill={`url(#${uid}-key)`}
          />
        </g>

        <g filter={`url(#${uid}-bokeh)`}>
          {art.bokeh.map((b, i) => (
            <ellipse
              key={i}
              cx={b.cx}
              cy={b.cy}
              rx={b.r}
              ry={b.r * 0.92}
              opacity={b.o}
              fill={`url(#${uid}-disc${b.warm ? '-warm' : ''})`}
            />
          ))}
          <rect
            x="-10"
            y={art.streakY}
            width="120"
            height="1"
            fill={`url(#${uid}-streak)`}
            transform={`rotate(${art.streakTilt} 50 ${art.streakY})`}
          />
        </g>

        <rect width="100" height="100" fill={`url(#${uid}-floor)`} />

        <rect width="100" height="100" fill={`url(#${uid}-vig)`} />
      </svg>
    </div>
  )
}
